spring:
  profiles:
    active: core, db
  message:
    encoding: UTF-8
  rabbitmq:
    host: 192.168.248.130
    port: 5672
    username: rabbit
    password: 123456
logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  DEBUG