package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPropertyUnit;
import org.linlinjava.litemall.db.domain.LitemallPropertyUnitExample;

public interface LitemallPropertyUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    long countByExample(LitemallPropertyUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPropertyUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int insert(LitemallPropertyUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPropertyUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyUnit selectOneByExample(LitemallPropertyUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyUnit selectOneByExampleSelective(@Param("example") LitemallPropertyUnitExample example, @Param("selective") LitemallPropertyUnit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPropertyUnit> selectByExampleSelective(@Param("example") LitemallPropertyUnitExample example, @Param("selective") LitemallPropertyUnit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    List<LitemallPropertyUnit> selectByExample(LitemallPropertyUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyUnit selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPropertyUnit.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    LitemallPropertyUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPropertyUnit record, @Param("example") LitemallPropertyUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPropertyUnit record, @Param("example") LitemallPropertyUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPropertyUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPropertyUnit record);
}