package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPropertyHouse;
import org.linlinjava.litemall.db.domain.LitemallPropertyHouseExample;

public interface LitemallPropertyHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    long countByExample(LitemallPropertyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPropertyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int insert(LitemallPropertyHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPropertyHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyHouse selectOneByExample(LitemallPropertyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyHouse selectOneByExampleSelective(@Param("example") LitemallPropertyHouseExample example, @Param("selective") LitemallPropertyHouse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPropertyHouse> selectByExampleSelective(@Param("example") LitemallPropertyHouseExample example, @Param("selective") LitemallPropertyHouse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    List<LitemallPropertyHouse> selectByExample(LitemallPropertyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyHouse selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPropertyHouse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    LitemallPropertyHouse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPropertyHouse record, @Param("example") LitemallPropertyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPropertyHouse record, @Param("example") LitemallPropertyHouseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPropertyHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPropertyHouse record);
}