package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPropertyPaymentRecord;
import org.linlinjava.litemall.db.domain.LitemallPropertyPaymentRecordExample;

public interface LitemallPropertyPaymentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    long countByExample(LitemallPropertyPaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPropertyPaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int insert(LitemallPropertyPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPropertyPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyPaymentRecord selectOneByExample(LitemallPropertyPaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyPaymentRecord selectOneByExampleSelective(@Param("example") LitemallPropertyPaymentRecordExample example, @Param("selective") LitemallPropertyPaymentRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPropertyPaymentRecord> selectByExampleSelective(@Param("example") LitemallPropertyPaymentRecordExample example, @Param("selective") LitemallPropertyPaymentRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    List<LitemallPropertyPaymentRecord> selectByExample(LitemallPropertyPaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyPaymentRecord selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPropertyPaymentRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    LitemallPropertyPaymentRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPropertyPaymentRecord record, @Param("example") LitemallPropertyPaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPropertyPaymentRecord record, @Param("example") LitemallPropertyPaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPropertyPaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPropertyPaymentRecord record);
}