package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallRepaircat;
import org.linlinjava.litemall.db.domain.LitemallRepaircatExample;

public interface LitemallRepaircatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    long countByExample(LitemallRepaircatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRepaircatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int insert(LitemallRepaircat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRepaircat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRepaircat selectOneByExample(LitemallRepaircatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRepaircat selectOneByExampleSelective(@Param("example") LitemallRepaircatExample example, @Param("selective") LitemallRepaircat.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallRepaircat> selectByExampleSelective(@Param("example") LitemallRepaircatExample example, @Param("selective") LitemallRepaircat.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    List<LitemallRepaircat> selectByExample(LitemallRepaircatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallRepaircat selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRepaircat.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    LitemallRepaircat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRepaircat record, @Param("example") LitemallRepaircatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRepaircat record, @Param("example") LitemallRepaircatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRepaircat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRepaircat record);
}