package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPropertyCommunity;
import org.linlinjava.litemall.db.domain.LitemallPropertyCommunityExample;

public interface LitemallPropertyCommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    long countByExample(LitemallPropertyCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPropertyCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int insert(LitemallPropertyCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPropertyCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyCommunity selectOneByExample(LitemallPropertyCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyCommunity selectOneByExampleSelective(@Param("example") LitemallPropertyCommunityExample example, @Param("selective") LitemallPropertyCommunity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPropertyCommunity> selectByExampleSelective(@Param("example") LitemallPropertyCommunityExample example, @Param("selective") LitemallPropertyCommunity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    List<LitemallPropertyCommunity> selectByExample(LitemallPropertyCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPropertyCommunity selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPropertyCommunity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    LitemallPropertyCommunity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPropertyCommunity record, @Param("example") LitemallPropertyCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPropertyCommunity record, @Param("example") LitemallPropertyCommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPropertyCommunity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_community
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPropertyCommunity record);
}