package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ShortMessage;
import org.linlinjava.litemall.db.domain.ShortMessageExample;

public interface ShortMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    long countByExample(ShortMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int deleteByExample(ShortMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int insert(ShortMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int insertSelective(ShortMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShortMessage selectOneByExample(ShortMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShortMessage selectOneByExampleSelective(@Param("example") ShortMessageExample example, @Param("selective") ShortMessage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShortMessage> selectByExampleSelective(@Param("example") ShortMessageExample example, @Param("selective") ShortMessage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    List<ShortMessage> selectByExample(ShortMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShortMessage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShortMessage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    ShortMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShortMessage record, @Param("example") ShortMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShortMessage record, @Param("example") ShortMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShortMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShortMessage record);
}