package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallPropertyHouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.community_id
     *
     * @mbg.generated
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.unit_id
     *
     * @mbg.generated
     */
    private Integer unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.doornum_id
     *
     * @mbg.generated
     */
    private Integer doornumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.create_date
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.community_name
     *
     * @mbg.generated
     */
    private String communityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.unit_name
     *
     * @mbg.generated
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.doornum
     *
     * @mbg.generated
     */
    private String doornum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.house_area
     *
     * @mbg.generated
     */
    private Double houseArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_property_house.monthly_fee
     *
     * @mbg.generated
     */
    private BigDecimal monthlyFee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.id
     *
     * @return the value of litemall_property_house.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.id
     *
     * @param id the value for litemall_property_house.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.community_id
     *
     * @return the value of litemall_property_house.community_id
     *
     * @mbg.generated
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.community_id
     *
     * @param communityId the value for litemall_property_house.community_id
     *
     * @mbg.generated
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.unit_id
     *
     * @return the value of litemall_property_house.unit_id
     *
     * @mbg.generated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.unit_id
     *
     * @param unitId the value for litemall_property_house.unit_id
     *
     * @mbg.generated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.doornum_id
     *
     * @return the value of litemall_property_house.doornum_id
     *
     * @mbg.generated
     */
    public Integer getDoornumId() {
        return doornumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.doornum_id
     *
     * @param doornumId the value for litemall_property_house.doornum_id
     *
     * @mbg.generated
     */
    public void setDoornumId(Integer doornumId) {
        this.doornumId = doornumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.create_date
     *
     * @return the value of litemall_property_house.create_date
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.create_date
     *
     * @param createDate the value for litemall_property_house.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.community_name
     *
     * @return the value of litemall_property_house.community_name
     *
     * @mbg.generated
     */
    public String getCommunityName() {
        return communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.community_name
     *
     * @param communityName the value for litemall_property_house.community_name
     *
     * @mbg.generated
     */
    public void setCommunityName(String communityName) {
        this.communityName = communityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.unit_name
     *
     * @return the value of litemall_property_house.unit_name
     *
     * @mbg.generated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.unit_name
     *
     * @param unitName the value for litemall_property_house.unit_name
     *
     * @mbg.generated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.doornum
     *
     * @return the value of litemall_property_house.doornum
     *
     * @mbg.generated
     */
    public String getDoornum() {
        return doornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.doornum
     *
     * @param doornum the value for litemall_property_house.doornum
     *
     * @mbg.generated
     */
    public void setDoornum(String doornum) {
        this.doornum = doornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.house_area
     *
     * @return the value of litemall_property_house.house_area
     *
     * @mbg.generated
     */
    public Double getHouseArea() {
        return houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.house_area
     *
     * @param houseArea the value for litemall_property_house.house_area
     *
     * @mbg.generated
     */
    public void setHouseArea(Double houseArea) {
        this.houseArea = houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_property_house.monthly_fee
     *
     * @return the value of litemall_property_house.monthly_fee
     *
     * @mbg.generated
     */
    public BigDecimal getMonthlyFee() {
        return monthlyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_property_house.monthly_fee
     *
     * @param monthlyFee the value for litemall_property_house.monthly_fee
     *
     * @mbg.generated
     */
    public void setMonthlyFee(BigDecimal monthlyFee) {
        this.monthlyFee = monthlyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", communityId=").append(communityId);
        sb.append(", unitId=").append(unitId);
        sb.append(", doornumId=").append(doornumId);
        sb.append(", createDate=").append(createDate);
        sb.append(", communityName=").append(communityName);
        sb.append(", unitName=").append(unitName);
        sb.append(", doornum=").append(doornum);
        sb.append(", houseArea=").append(houseArea);
        sb.append(", monthlyFee=").append(monthlyFee);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallPropertyHouse other = (LitemallPropertyHouse) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCommunityId() == null ? other.getCommunityId() == null : this.getCommunityId().equals(other.getCommunityId()))
            && (this.getUnitId() == null ? other.getUnitId() == null : this.getUnitId().equals(other.getUnitId()))
            && (this.getDoornumId() == null ? other.getDoornumId() == null : this.getDoornumId().equals(other.getDoornumId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getCommunityName() == null ? other.getCommunityName() == null : this.getCommunityName().equals(other.getCommunityName()))
            && (this.getUnitName() == null ? other.getUnitName() == null : this.getUnitName().equals(other.getUnitName()))
            && (this.getDoornum() == null ? other.getDoornum() == null : this.getDoornum().equals(other.getDoornum()))
            && (this.getHouseArea() == null ? other.getHouseArea() == null : this.getHouseArea().equals(other.getHouseArea()))
            && (this.getMonthlyFee() == null ? other.getMonthlyFee() == null : this.getMonthlyFee().equals(other.getMonthlyFee()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCommunityId() == null) ? 0 : getCommunityId().hashCode());
        result = prime * result + ((getUnitId() == null) ? 0 : getUnitId().hashCode());
        result = prime * result + ((getDoornumId() == null) ? 0 : getDoornumId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getCommunityName() == null) ? 0 : getCommunityName().hashCode());
        result = prime * result + ((getUnitName() == null) ? 0 : getUnitName().hashCode());
        result = prime * result + ((getDoornum() == null) ? 0 : getDoornum().hashCode());
        result = prime * result + ((getHouseArea() == null) ? 0 : getHouseArea().hashCode());
        result = prime * result + ((getMonthlyFee() == null) ? 0 : getMonthlyFee().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_property_house
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        communityId("community_id", "communityId", "INTEGER", false),
        unitId("unit_id", "unitId", "INTEGER", false),
        doornumId("doornum_id", "doornumId", "INTEGER", false),
        createDate("create_date", "createDate", "TIMESTAMP", false),
        communityName("community_name", "communityName", "VARCHAR", false),
        unitName("unit_name", "unitName", "VARCHAR", false),
        doornum("doornum", "doornum", "VARCHAR", false),
        houseArea("house_area", "houseArea", "DOUBLE", false),
        monthlyFee("monthly_fee", "monthlyFee", "DECIMAL", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_property_house
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}