package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallRepaircat2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repaircat2.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repaircat2.repaircat_id
     *
     * @mbg.generated
     */
    private Integer repaircatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repaircat2.category2
     *
     * @mbg.generated
     */
    private String category2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repaircat2.labour_cost
     *
     * @mbg.generated
     */
    private Double labourCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repaircat2.timeout_charge
     *
     * @mbg.generated
     */
    private BigDecimal timeoutCharge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repaircat2.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repaircat2.id
     *
     * @return the value of litemall_repaircat2.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repaircat2.id
     *
     * @param id the value for litemall_repaircat2.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repaircat2.repaircat_id
     *
     * @return the value of litemall_repaircat2.repaircat_id
     *
     * @mbg.generated
     */
    public Integer getRepaircatId() {
        return repaircatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repaircat2.repaircat_id
     *
     * @param repaircatId the value for litemall_repaircat2.repaircat_id
     *
     * @mbg.generated
     */
    public void setRepaircatId(Integer repaircatId) {
        this.repaircatId = repaircatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repaircat2.category2
     *
     * @return the value of litemall_repaircat2.category2
     *
     * @mbg.generated
     */
    public String getCategory2() {
        return category2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repaircat2.category2
     *
     * @param category2 the value for litemall_repaircat2.category2
     *
     * @mbg.generated
     */
    public void setCategory2(String category2) {
        this.category2 = category2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repaircat2.labour_cost
     *
     * @return the value of litemall_repaircat2.labour_cost
     *
     * @mbg.generated
     */
    public Double getLabourCost() {
        return labourCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repaircat2.labour_cost
     *
     * @param labourCost the value for litemall_repaircat2.labour_cost
     *
     * @mbg.generated
     */
    public void setLabourCost(Double labourCost) {
        this.labourCost = labourCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repaircat2.timeout_charge
     *
     * @return the value of litemall_repaircat2.timeout_charge
     *
     * @mbg.generated
     */
    public BigDecimal getTimeoutCharge() {
        return timeoutCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repaircat2.timeout_charge
     *
     * @param timeoutCharge the value for litemall_repaircat2.timeout_charge
     *
     * @mbg.generated
     */
    public void setTimeoutCharge(BigDecimal timeoutCharge) {
        this.timeoutCharge = timeoutCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repaircat2.remarks
     *
     * @return the value of litemall_repaircat2.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repaircat2.remarks
     *
     * @param remarks the value for litemall_repaircat2.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat2
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", repaircatId=").append(repaircatId);
        sb.append(", category2=").append(category2);
        sb.append(", labourCost=").append(labourCost);
        sb.append(", timeoutCharge=").append(timeoutCharge);
        sb.append(", remarks=").append(remarks);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat2
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallRepaircat2 other = (LitemallRepaircat2) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRepaircatId() == null ? other.getRepaircatId() == null : this.getRepaircatId().equals(other.getRepaircatId()))
            && (this.getCategory2() == null ? other.getCategory2() == null : this.getCategory2().equals(other.getCategory2()))
            && (this.getLabourCost() == null ? other.getLabourCost() == null : this.getLabourCost().equals(other.getLabourCost()))
            && (this.getTimeoutCharge() == null ? other.getTimeoutCharge() == null : this.getTimeoutCharge().equals(other.getTimeoutCharge()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repaircat2
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRepaircatId() == null) ? 0 : getRepaircatId().hashCode());
        result = prime * result + ((getCategory2() == null) ? 0 : getCategory2().hashCode());
        result = prime * result + ((getLabourCost() == null) ? 0 : getLabourCost().hashCode());
        result = prime * result + ((getTimeoutCharge() == null) ? 0 : getTimeoutCharge().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_repaircat2
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        repaircatId("repaircat_id", "repaircatId", "INTEGER", false),
        category2("category2", "category2", "VARCHAR", false),
        labourCost("labour_cost", "labourCost", "DOUBLE", false),
        timeoutCharge("timeout_charge", "timeoutCharge", "DECIMAL", false),
        remarks("remarks", "remarks", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repaircat2
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}