package org.linlinjava.litemall.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallRepair {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.repair_type
     *
     * @mbg.generated
     */
    private Integer repairType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.category2_id
     *
     * @mbg.generated
     */
    private Integer category2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.img_1
     *
     * @mbg.generated
     */
    private String img1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.img_2
     *
     * @mbg.generated
     */
    private String img2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.img_3
     *
     * @mbg.generated
     */
    private String img3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.update_date
     *
     * @mbg.generated
     */
    private LocalDateTime updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.scheduled_date
     *
     * @mbg.generated
     */
    private LocalDateTime scheduledDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.paymoney
     *
     * @mbg.generated
     */
    private BigDecimal paymoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.payment_status
     *
     * @mbg.generated
     */
    private Integer paymentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.comment_status
     *
     * @mbg.generated
     */
    private Integer commentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_repair.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.id
     *
     * @return the value of litemall_repair.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.id
     *
     * @param id the value for litemall_repair.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.member_id
     *
     * @return the value of litemall_repair.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.member_id
     *
     * @param memberId the value for litemall_repair.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.repair_type
     *
     * @return the value of litemall_repair.repair_type
     *
     * @mbg.generated
     */
    public Integer getRepairType() {
        return repairType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.repair_type
     *
     * @param repairType the value for litemall_repair.repair_type
     *
     * @mbg.generated
     */
    public void setRepairType(Integer repairType) {
        this.repairType = repairType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.category_id
     *
     * @return the value of litemall_repair.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.category_id
     *
     * @param categoryId the value for litemall_repair.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.category2_id
     *
     * @return the value of litemall_repair.category2_id
     *
     * @mbg.generated
     */
    public Integer getCategory2Id() {
        return category2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.category2_id
     *
     * @param category2Id the value for litemall_repair.category2_id
     *
     * @mbg.generated
     */
    public void setCategory2Id(Integer category2Id) {
        this.category2Id = category2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.title
     *
     * @return the value of litemall_repair.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.title
     *
     * @param title the value for litemall_repair.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.content
     *
     * @return the value of litemall_repair.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.content
     *
     * @param content the value for litemall_repair.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.img_1
     *
     * @return the value of litemall_repair.img_1
     *
     * @mbg.generated
     */
    public String getImg1() {
        return img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.img_1
     *
     * @param img1 the value for litemall_repair.img_1
     *
     * @mbg.generated
     */
    public void setImg1(String img1) {
        this.img1 = img1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.img_2
     *
     * @return the value of litemall_repair.img_2
     *
     * @mbg.generated
     */
    public String getImg2() {
        return img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.img_2
     *
     * @param img2 the value for litemall_repair.img_2
     *
     * @mbg.generated
     */
    public void setImg2(String img2) {
        this.img2 = img2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.img_3
     *
     * @return the value of litemall_repair.img_3
     *
     * @mbg.generated
     */
    public String getImg3() {
        return img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.img_3
     *
     * @param img3 the value for litemall_repair.img_3
     *
     * @mbg.generated
     */
    public void setImg3(String img3) {
        this.img3 = img3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.address
     *
     * @return the value of litemall_repair.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.address
     *
     * @param address the value for litemall_repair.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.update_date
     *
     * @return the value of litemall_repair.update_date
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.update_date
     *
     * @param updateDate the value for litemall_repair.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.scheduled_date
     *
     * @return the value of litemall_repair.scheduled_date
     *
     * @mbg.generated
     */
    public LocalDateTime getScheduledDate() {
        return scheduledDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.scheduled_date
     *
     * @param scheduledDate the value for litemall_repair.scheduled_date
     *
     * @mbg.generated
     */
    public void setScheduledDate(LocalDateTime scheduledDate) {
        this.scheduledDate = scheduledDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.paymoney
     *
     * @return the value of litemall_repair.paymoney
     *
     * @mbg.generated
     */
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.paymoney
     *
     * @param paymoney the value for litemall_repair.paymoney
     *
     * @mbg.generated
     */
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.payment_status
     *
     * @return the value of litemall_repair.payment_status
     *
     * @mbg.generated
     */
    public Integer getPaymentStatus() {
        return paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.payment_status
     *
     * @param paymentStatus the value for litemall_repair.payment_status
     *
     * @mbg.generated
     */
    public void setPaymentStatus(Integer paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.status
     *
     * @return the value of litemall_repair.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.status
     *
     * @param status the value for litemall_repair.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.comment
     *
     * @return the value of litemall_repair.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.comment
     *
     * @param comment the value for litemall_repair.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.comment_status
     *
     * @return the value of litemall_repair.comment_status
     *
     * @mbg.generated
     */
    public Integer getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.comment_status
     *
     * @param commentStatus the value for litemall_repair.comment_status
     *
     * @mbg.generated
     */
    public void setCommentStatus(Integer commentStatus) {
        this.commentStatus = commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_repair.category
     *
     * @return the value of litemall_repair.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_repair.category
     *
     * @param category the value for litemall_repair.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repair
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", memberId=").append(memberId);
        sb.append(", repairType=").append(repairType);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", category2Id=").append(category2Id);
        sb.append(", title=").append(title);
        sb.append(", content=").append(content);
        sb.append(", img1=").append(img1);
        sb.append(", img2=").append(img2);
        sb.append(", img3=").append(img3);
        sb.append(", address=").append(address);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", scheduledDate=").append(scheduledDate);
        sb.append(", paymoney=").append(paymoney);
        sb.append(", paymentStatus=").append(paymentStatus);
        sb.append(", status=").append(status);
        sb.append(", comment=").append(comment);
        sb.append(", commentStatus=").append(commentStatus);
        sb.append(", category=").append(category);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repair
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallRepair other = (LitemallRepair) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMemberId() == null ? other.getMemberId() == null : this.getMemberId().equals(other.getMemberId()))
            && (this.getRepairType() == null ? other.getRepairType() == null : this.getRepairType().equals(other.getRepairType()))
            && (this.getCategoryId() == null ? other.getCategoryId() == null : this.getCategoryId().equals(other.getCategoryId()))
            && (this.getCategory2Id() == null ? other.getCategory2Id() == null : this.getCategory2Id().equals(other.getCategory2Id()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getImg1() == null ? other.getImg1() == null : this.getImg1().equals(other.getImg1()))
            && (this.getImg2() == null ? other.getImg2() == null : this.getImg2().equals(other.getImg2()))
            && (this.getImg3() == null ? other.getImg3() == null : this.getImg3().equals(other.getImg3()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getScheduledDate() == null ? other.getScheduledDate() == null : this.getScheduledDate().equals(other.getScheduledDate()))
            && (this.getPaymoney() == null ? other.getPaymoney() == null : this.getPaymoney().equals(other.getPaymoney()))
            && (this.getPaymentStatus() == null ? other.getPaymentStatus() == null : this.getPaymentStatus().equals(other.getPaymentStatus()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getComment() == null ? other.getComment() == null : this.getComment().equals(other.getComment()))
            && (this.getCommentStatus() == null ? other.getCommentStatus() == null : this.getCommentStatus().equals(other.getCommentStatus()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_repair
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMemberId() == null) ? 0 : getMemberId().hashCode());
        result = prime * result + ((getRepairType() == null) ? 0 : getRepairType().hashCode());
        result = prime * result + ((getCategoryId() == null) ? 0 : getCategoryId().hashCode());
        result = prime * result + ((getCategory2Id() == null) ? 0 : getCategory2Id().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getImg1() == null) ? 0 : getImg1().hashCode());
        result = prime * result + ((getImg2() == null) ? 0 : getImg2().hashCode());
        result = prime * result + ((getImg3() == null) ? 0 : getImg3().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getScheduledDate() == null) ? 0 : getScheduledDate().hashCode());
        result = prime * result + ((getPaymoney() == null) ? 0 : getPaymoney().hashCode());
        result = prime * result + ((getPaymentStatus() == null) ? 0 : getPaymentStatus().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getComment() == null) ? 0 : getComment().hashCode());
        result = prime * result + ((getCommentStatus() == null) ? 0 : getCommentStatus().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_repair
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        memberId("member_id", "memberId", "INTEGER", false),
        repairType("repair_type", "repairType", "INTEGER", false),
        categoryId("category_id", "categoryId", "INTEGER", false),
        category2Id("category2_id", "category2Id", "INTEGER", false),
        title("title", "title", "VARCHAR", false),
        content("content", "content", "VARCHAR", false),
        img1("img_1", "img1", "VARCHAR", false),
        img2("img_2", "img2", "VARCHAR", false),
        img3("img_3", "img3", "VARCHAR", false),
        address("address", "address", "VARCHAR", false),
        updateDate("update_date", "updateDate", "TIMESTAMP", false),
        scheduledDate("scheduled_date", "scheduledDate", "TIMESTAMP", false),
        paymoney("paymoney", "paymoney", "DECIMAL", false),
        paymentStatus("payment_status", "paymentStatus", "INTEGER", false),
        status("status", "status", "INTEGER", true),
        comment("comment", "comment", "VARCHAR", true),
        commentStatus("comment_status", "commentStatus", "INTEGER", false),
        category("category", "category", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_repair
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}